"""IsoExec execution contract: types, canonical serialization, identities, validation."""

from .identity import (
    compute_identities,
    deployment_half,
    function_half,
    semantic_inputs,
)
from .serialize import (
    SUPPORTED_SCHEMA_VERSIONS,
    SerializationError,
    UnknownFieldError,
    from_canonical_json,
    to_canonical_json,
)
from .types import (
    COVERAGE_KINDS,
    DISCHARGE_KINDS,
    HALVES,
    ROUTES,
    TOPOLOGY_KINDS,
    BitPattern,
    Claims,
    CompositionEntry,
    Coverage,
    EquivalenceProof,
    ExecutionCase,
    ExecutionContract,
    Identities,
    ImplRef,
    ModelRef,
    StateClaim,
    ToleranceClaim,
    TopologyClaim,
)
from .validate import ValidationError, validate, validate_or_raise

__all__ = [
    "BitPattern",
    "ExecutionCase",
    "Claims",
    "Coverage",
    "EquivalenceProof",
    "CompositionEntry",
    "ExecutionContract",
    "Identities",
    "ImplRef",
    "ModelRef",
    "StateClaim",
    "ToleranceClaim",
    "TopologyClaim",
    "ROUTES",
    "DISCHARGE_KINDS",
    "COVERAGE_KINDS",
    "HALVES",
    "TOPOLOGY_KINDS",
    "SUPPORTED_SCHEMA_VERSIONS",
    "SerializationError",
    "UnknownFieldError",
    "to_canonical_json",
    "from_canonical_json",
    "compute_identities",
    "function_half",
    "deployment_half",
    "semantic_inputs",
    "ValidationError",
    "validate",
    "validate_or_raise",
]
